### PR TITLE
make sure we build this every day

### PR DESCRIPTION
**Pull request by yyolk**
also adds testing declarative pipeline triggers in our setup

### CODE REVIEW

**Comment by yyolk** [comment]
Nice!

**Comment by maflaven** [comment]
I figured you wouldn't mind me taking another stab at this @yyolk .

**Comment by yyolk** [comment]
@ranginuitrot s it worth investigating to see if we should set `TZ`?

**Comment by maflaven** [comment]
There's no explicit syntax for that here https://jenkins.io/doc/book/pipeline/syntax/#cron-syntax
It might be supported as indicated here https://en.wikipedia.org/wiki/Cron#Timezone_handling, but that also notes that cron follows the invocation env timezone.

**Comment by yyolk** [comment]
@ranginuitrot that makes sense, [I'm using this to generate the syntax](https://jenkins.arturo.ai/job/AmFamLabs/job/builder-python/directive-generator/):
image

**Pull request merged**
